services:
  - type: web
    name: ic-migue-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    autoDeploy: true
